# Base image Debian 6.0 Squeeze
FROM debian:squeeze

MAINTAINER Gian Marco Sibilla <gm.sibilla@gmail.com>

# Add debian non-free packages
# RUN echo "deb http://httpredir.debian.org/debian squeeze main contrib non-free" >> /etc/apt/sources.list.d/debian-non-free.list

# Install wget
RUN apt-get update && apt-get install -y --force-yes \
 wget \
 gcc \
 make \
 # sun-java6-jdk \
 python \
 alien

# NOT WORKING!!
# # Add TinyOS cert
# RUN wget http://tinyprod.net/repos/debian/tinyprod.key
# RUN gpg --keyserver keyring.debian.org --recv-keys A9B913B9
# RUN gpg -a --export A9B913B9
# RUN apt-key add tinyprod.key | rm tinyprod.key
# # Add deb package
# RUN echo "deb http://tinyprod.net/repos/debian squeeze main" >> /etc/apt/sources.list.d/tinyprod-debian.list
# RUN echo "deb http://tinyprod.net/repos/debian msp430-46 main" >> /etc/apt/sources.list.d/tinyprod-debian.list
# Install TinyOS and required packages
# RUN apt-get update & apt-get -y install nesc tinyos-tools msp430-46 avr-tinyos
WORKDIR /tmp

# Install Java JDK
RUN wget --no-check-certificate --header "Cookie: oraclelicense=accept-securebackup-cookie" -O jdk7.tar.gz http://download.oracle.com/otn-pub/java/jdk/7u79-b15/jdk-7u79-linux-x64.tar.gz
RUN mkdir -p /usr/local/opt/jdk && tar zxf jdk7.tar.gz -C /usr/local/opt/jdk
RUN update-alternatives --install /usr/bin/java java /usr/local/opt/jdk/jdk1.7.0_79/bin/java 100
RUN update-alternatives --install /usr/bin/javac javac /usr/local/opt/jdk/jdk1.7.0_79/bin/javac 100

# Install native Atmel AVR compilers
RUN wget -O avr-binutils.rpm http://www.tinyos.net/dist-2.1.0/tools/linux/avr-binutils-2.17tinyos-3.i386.rpm && alien -i avr-binutils.rpm
RUN wget -O avr-gcc.rpm http://www.tinyos.net/dist-2.1.0/tools/linux/avr-gcc-4.1.2-1.i386.rpm && && alien -i avr-gcc.rpm
RUN wget -O avr-libc.rpm http://www.tinyos.net/dist-2.1.0/tools/linux/avr-libc-1.4.7-1.i386.rpm && && alien -i avr-libc.rpm
RUN wget -O avarice.rpm http://www.tinyos.net/dist-2.1.0/tools/linux/avarice-2.4-1.i386.rpm && alien -i avarice.rpm
RUN wget -O avr-insight.rpm http://www.tinyos.net/dist-2.1.0/tools/linux/avr-insight-6.3-1.i386.rpm && alien -i avr-insight
RUN wget -O avrdude.rpm http://www.tinyos.net/dist-2.1.0/tools/linux/avrdude-tinyos-5.6cvs-1.i386.rpm&& alien -i avrdude.rpm
# TinyOS toolchain
RUN wget -O nesc.rpm http://tinyos.stanford.edu/tinyos-rpms/nesc-1.3.1-1.fc9.i386.rpm && alien -i nesc.rpm
RUN wget -O deputy.rpm http://www.tinyos.net/dist-2.1.0/tinyos/linux/tinyos-deputy-1.1-1.fc9.i386.rpm && alien -i deputy.rpm
RUN wget -O tinyos-tools.rpm http://tinyos.stanford.edu/tinyos-rpms/tinyos-tools-1.4.0-3.ubuntu.i386.rpm && alien -i tinyos-tools.rpm

# Download and decompress TinyOS sources
RUN wget -O tinyos-2_1_2.tar.gz wget --no-check-certificate http://github.com/tinyos/tinyos-release/archive/tinyos-2_1_2.tar.gz
RUN mkdir -p /usr/local/opt & tar xf tinyos-2_1_2.tar.gz -C /usr/local/opt
RUN mv /usr/local/opt/tinyos-release-tinyos-2_1_2 /usr/local/opt/tinyos-main

# Export environment variables required for TinyOS
ENV TOSROOT="/usr/local/opt/tinyos-main"
ENV TOSDIR="$TOSROOT/tos"
ENV CLASSPATH=$CLASSPATH:$TOSROOT/support/sdk/java
ENV MAKERULES="$TOSROOT/support/make/Makerules"
ENV PYTHONPATH=$PYTHONPATH:$TOSROOT/support/sdk/python

RUN useradd -d /tinyos -g sudo -G dialout -p tinyos tinyos

WORKDIR /
